/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinhtruong
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */

    
    
    private int id_bill;
    // use to see info and edit data 
    private String id_product;
    
    private int action;
    
    /*
        action = 0 : see table
        action = 1 : see info
        action = 2 : add
    */
    public bill() {
        initComponents();
        this.id_bill = 0;
        this.action = 0;
        this.id_product = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill_info = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_id_product = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        js_count = new javax.swing.JSpinner();
        btn_del_bill_info = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_bill_info = new javax.swing.JTable();
        pal_info = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txt_id_customer = new javax.swing.JFormattedTextField();
        jPanel35 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jcb_payment = new javax.swing.JComboBox<>();
        jPanel36 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        lb_sale = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lb_sum_bill = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lb_shell_out = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_note = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        btn_ok = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_bill = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_load = new javax.swing.JButton();
        btn_info = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jcb_search = new javax.swing.JComboBox<>();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();

        bill_info.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bill_info.setSize(new java.awt.Dimension(970, 680));
        bill_info.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                bill_infoWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                bill_infoWindowActivated(evt);
            }
        });

        lb_title.setText("Title");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(lb_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("ID Product:");

        txt_id_product.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_id_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_productActionPerformed(evt);
            }
        });

        jLabel8.setText("X");

        js_count.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btn_del_bill_info.setText("Delete Product");
        btn_del_bill_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del_bill_infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id_product, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_count, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_del_bill_info, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_id_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(js_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_del_bill_info))
                .addContainerGap())
        );

        jtb_bill_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Product", "Name Product", "Price", "Sale", "Count", "Total"
            }
        ));
        jtb_bill_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_bill_infoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtb_bill_info);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pal_info.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pal_info.setPreferredSize(new java.awt.Dimension(330, 606));

        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel20.setText("Infomation Bill");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20)
        );

        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setText("ID Customer:");

        txt_id_customer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txt_id_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_customerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_id_customer))
                .addContainerGap())
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("Pay:");

        jcb_payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Use Cash", "Use Card" }));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jcb_payment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Sale:");

        lb_sale.setText("0");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lb_sale))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setText("Total bill:");

        lb_sum_bill.setText("0");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(lb_sum_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lb_sum_bill))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Rest:");

        lb_shell_out.setText("0");

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lb_shell_out, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lb_shell_out))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Note:");

        txt_note.setColumns(20);
        txt_note.setRows(5);
        jScrollPane5.setViewportView(txt_note);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pal_infoLayout = new javax.swing.GroupLayout(pal_info);
        pal_info.setLayout(pal_infoLayout);
        pal_infoLayout.setHorizontalGroup(
            pal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pal_infoLayout.setVerticalGroup(
            pal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(518, 518, 518)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout bill_infoLayout = new javax.swing.GroupLayout(bill_info.getContentPane());
        bill_info.getContentPane().setLayout(bill_infoLayout);
        bill_infoLayout.setHorizontalGroup(
            bill_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bill_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bill_infoLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pal_info, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bill_infoLayout.setVerticalGroup(
            bill_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bill_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bill_infoLayout.createSequentialGroup()
                        .addComponent(pal_info, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtb_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Bill", "Customer", "Staff", "Date", "Payment", "Sale", "Total"
            }
        ));
        jtb_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_bill);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Management Bill");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(514, 514, 514))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btn_load.setText("Load");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        btn_info.setText("Infomation");
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_del.setText("Del");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_info, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_info)
                    .addComponent(btn_add)
                    .addComponent(btn_del)
                    .addComponent(btn_back)
                    .addComponent(btn_load))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcb_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search ID Bill", "Search Name Customer", "Search Name Staff", "Search Date", "Search Pay" }));

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcb_search, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //---------------------------------         Function use frame  ----------------------------------
    
    BLL.bll_bill bll = new BLL.bll_bill();
    
    BLL.bll_bill_info bll_info = new BLL.bll_bill_info();
    
    BLL.bll_staff bll_staff = new BLL.bll_staff();
    
    BLL.bll_customer bll_customer = new BLL.bll_customer();
    
    BLL.bll_product bll_product = new BLL.bll_product();
    
    private DefaultTableModel model = new DefaultTableModel();
    
    
    private String Date_Now()
    {
        LocalDateTime x = LocalDateTime.now();
        String date = x.format(DateTimeFormatter.ISO_LOCAL_DATE);
        return date;
    }
    
    private String Time_Now()
    {
        LocalDateTime x = LocalDateTime.now();
        String Time = x.format(DateTimeFormatter.ISO_LOCAL_TIME);
        String t = Time.substring(0,8);
        return t;
    }
    
    
    
    /*
        Hàm load các sản phẩm có trong DataBase
    */
    
    //Load data in JTable Bill
    private void Load()
    {
        
        //String header_vi[] = {""};
        //String header_en[] = {};        
        
        model = (DefaultTableModel) jtb_bill.getModel();
        if(model.getRowCount() > 0)
            model.setRowCount(0);//trả về table rỗng
        // Nhap lieu vao table
        ArrayList<DTO.bill> List_bill = bll.List_Bill();
        for (DTO.bill bill : List_bill)
            AddRow(bill);
    }
    
    
    
    /*
        Hàm đưa giá trị của sản phẩm vào Jtable Bill
    */
    
    private String Name_Customer(String id)
    {
        if(id == null || id.equals("") == true) return null;
        else
        {
            DTO.customer kh = bll_customer.Info_Customer(id);
            return kh.getFirst_name()+ " " + kh.getLast_name();
        }
    }
    
    private String Name_Staff(String id)
    {
        if(id == null || id.equals("") == true) return null;
        else
        {
            DTO.staff nv = bll_staff.Info_Staff(id);
            return nv.getFirst_name()+" "+ nv.getLast_name();
        }
    }
    
    //Get name Payment
    private String Name_Pay(int pay)
    {
        if(pay == 0 ) return "Use Cash";
        return "Use Card";
    }
    //Add data in Jtable BIll
    private void AddRow(DTO.bill bill)
    {
        model = (DefaultTableModel) jtb_bill.getModel();
        model.addRow(new Object[] {bill.getId(), Name_Customer(bill.getId_customer()), Name_Staff(bill.getId_staff()),bill.getDatetime(), Name_Pay(bill.getPayment()), bill.getSale(), bill.getShell_out()});
    }
    
    
    
    //Load data in database to JTable Bill Info
    private void Load_Bill_Info()
    {
        model = (DefaultTableModel) jtb_bill_info.getModel();
        if(model.getRowCount() > 0)
            model.setRowCount(0);//trả về table rỗng
        // Nhap lieu vao table
        ArrayList<DTO.bill_info> List_bill_info = bll_info.List_Bill_Info(this.id_bill);
        for (DTO.bill_info bill : List_bill_info)
            AddRow_Bill_Info(bill);
        
        lb_sum_bill.setText(String.valueOf(bll_info.Sum_Bill(id_bill)));
        if(Integer.parseInt(lb_sale.getText()) ==  0)
            lb_shell_out.setText(String.valueOf(bll_info.Sum_Bill(id_bill)));
    }
    
    //Add data in Jtable Bill info
    private void AddRow_Bill_Info(DTO.bill_info bill)
    {
        model = (DefaultTableModel) jtb_bill_info.getModel();
        model.addRow(new Object[] {bill.getId_product(), bll_product.Get_Name_Product_By_ID(bill.getId_product()), bill.getPrice(), bill.getSale(), bill.getCount(), bill.getSum()});
    }
    
    /*
        Hàm đưa dữ liệu từ Table ra co TextBox, Combobox
    */
    
    //Get ID Bill from JTable
    private void On_Click_JTable_Bill()
    {
        model = (DefaultTableModel) jtb_bill.getModel();
        this.id_bill = Integer.parseInt(model.getValueAt(jtb_bill.getSelectedRow(),0).toString());
        //System.out.println(this.id_bill);
    }
    
    //Get ID Product from JTable Bill Info
    private void On_Click_JTable_Bill_Info()
    {
        model = (DefaultTableModel) jtb_bill_info.getModel();
        this.id_product = (model.getValueAt(jtb_bill_info.getSelectedRow(),0).toString()); 
        //System.out.println(this.id_product);
    }
    
    //Get ID staff by Username of Staff
    private String ID_Staff(String UserName)
    {
        DTO.staff nv = bll_staff.Info_Staff_By_User_Name(UserName);
        return nv.getId();
    }
    
    
    /*
        Hàm sử dụng cho Add, Update, Del. Đưa thông tin từ TextBox, Combobox vào đối tượng sản phẩm
    */
     private DTO.bill Get_Form()
    {
        DTO.bill bill = new DTO.bill();
        bill.setId_customer(txt_id_customer.getText());
        DTO.customer customer = bll_customer.Info_Customer(txt_id_customer.getText());
        bill.setId_staff(this.ID_Staff(DTO.Static_Object.username));
        bill.setDatetime(Date_Now()+" "+Time_Now());
        bill.setPayment(jcb_payment.getSelectedIndex());
        bill.setSum_bill(Long.parseLong(lb_sum_bill.getText()));
        bill.setSale(Integer.parseInt(lb_sale.getText()));
        bill.setNote(txt_note.getText());
        bill.setShell_out(Long.parseLong(lb_shell_out.getText()));
        bill.setId(this.id_bill);
       
        return bill;
    }
    
     /*
        Hàm sử dụng để tìm kiếm các sản phẩm thỏa mãn với từ nvóa
     */
     
     
    private void Search()
    {
        model = (DefaultTableModel) jtb_bill.getModel();
        if(model.getRowCount() > 0)
            model.setRowCount(0);//trả về table rỗng
        
        if(txt_search.getText().equals("") == true)
            JOptionPane.showMessageDialog(null, "You must write \"Key word\"");
        ArrayList <DTO.bill> List_Bill_Search = bll.List_Search((jcb_search.getSelectedIndex()+1),txt_search.getText());
        for( DTO.bill bill : List_Bill_Search)
            AddRow(bill);
    }
     
    
    /*
        Hàm xóa các giá trị có trong textbox, combox
    */
    
    //Clear Control in jFrame Add, Edit
    private void Clear()
    {
            this.txt_id_customer.setText("");
            this.jcb_payment.setSelectedIndex(0);
            this.txt_note.setText("");
            this.lb_sum_bill.setText("0");
            this.lb_sale.setText("0");
            this.lb_shell_out.setText("0");
            this.txt_id_product.setText("");
    }
    
    // Check value "sale" of Customer
    private int Sale(String id_customer)
    {
        int rank = bll_customer.Check_Rank(id_customer);
        return bll.Check_Sale(rank);
    }
    
    
    
    //Get Info of Bill  set Control in jFrame Add, Edit
    private void Info_Bill()
    {
        DTO.bill bill = bll.Info_Bill(this.id_bill);
            this.txt_id_customer.setText(bill.getId_customer());
            this.jcb_payment.setSelectedIndex(bill.getPayment());
            this.lb_sum_bill.setText(String.valueOf(bill.getSum_bill()));
            this.lb_sale.setText(String.valueOf((bill.getSale())));
            this.lb_shell_out.setText(String.valueOf(bill.getShell_out()));
    }
    
    //Only use Get Info Bill
    private void See_Info()
    {
            this.txt_id_product.setEditable(false);
            this.txt_id_customer.setEditable(false);
            this.jcb_payment.setEditable(false);
            this.btn_del_bill_info.setVisible(false);
            this.btn_ok.setVisible(false);
    }
    
    //Reset Value control frame
    private void Close_Info()
    {
            this.txt_id_product.setEditable(true);
            this.txt_id_customer.setEditable(true);
            this.jcb_payment.setEditable(true);
            this.btn_del_bill_info.setVisible(true);
            this.btn_ok.setVisible(true);
    }
    
    // check before Add 
    private boolean Check()
    {
        if(txt_id_customer.getText().equals("") == true)
        {
            JOptionPane.showMessageDialog(null, "You don't text \"ID Customer\" is null");
                return false;
        } 
        return true;
    }
     
    
    
    // --------------------------------           End         ----------------------------------
    
    
    private void jtb_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_billMouseClicked
        On_Click_JTable_Bill();
    }//GEN-LAST:event_jtb_billMouseClicked

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        Load();
    }//GEN-LAST:event_btn_loadActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        if(this.id_bill == 0)
        {
            JOptionPane.showMessageDialog(null, "You must select item bill");
        }
        else
        {
            See_Info();
            Info_Bill();
            this.action = 1;
            this.bill_info.setVisible(true);
            this.bill_info.setSize(1250, 666);
            this.lb_title.setText("Infomation");
            
        }
    }//GEN-LAST:event_btn_infoActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        this.id_bill = bll.Get_Max_ID_Bill();
        DTO.bill bill = new DTO.bill();
        bill.setId(this.id_bill);
        bill.setDatetime(Date_Now() + " " + Time_Now());
        bill.setId_staff(this.ID_Staff(DTO.Static_Object.username));
        bll.Add(bill);
        this.action = 2;
        this.bill_info.setVisible(true);
        this.bill_info.setSize(1250, 666);
        lb_title.setText("Add");
        DTO.Static_Object.list_bill_info = null;
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_id_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_productActionPerformed
        String id_product = txt_id_product.getText();
        txt_id_product.setText("");
        if(bll_product.Check_Product(id_product) != true)
        JOptionPane.showMessageDialog(null, "ID doesn't exist");
        else
        {
            if(bll_info.Check_Bill_Info(id_bill, id_product) == true )
            {
                if(bll_product.Check_Count_Product(id_product) == true)
                {
                    System.out.println(id_bill);
                    DTO.product  info_product = bll_product.Info_Product(id_product);
                    DTO.bill_info bill_info = new DTO.bill_info();
                    bill_info.setId_bill(this.id_bill);
                    bill_info.setId_product(id_product);
                    bill_info.setCount((int) js_count.getValue());
                    bill_info.setPrice(info_product.getPrice());
                    bill_info.setSale(info_product.getSale());
                    long price = info_product.getPrice();
                    long count = (int) js_count.getValue();
                    long sale = (long) info_product.getSale();

                    if(info_product.getSale() != 0)
                        bill_info.setSum(((price * (100 - sale))/100) * count);
                    else 
                        bill_info.setSum(price * count);

                    bll_info.Add(bill_info, this.id_bill);
                    bll_product.Update_Count_Product(bill_info.getId_product(), 0, bill_info.getCount());
                }
                else
                    JOptionPane.showMessageDialog(null, "Count Product is null! Please create receive product");
            }
        }
    }//GEN-LAST:event_txt_id_productActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        if(this.action == 2)
        {
            bll_customer.Update_Accumulation(this.txt_id_customer.getText(), Long.parseLong(this.lb_sum_bill.getText()));
            bll_customer.Grownup_Rank(this.txt_id_customer.getText());
            DTO.bill bill =  Get_Form();
            if(bill.getId_customer().equals("") ==  false)
            bll.Update(bill);
            else bll.Update2(bill); // ham nay su dung ngoai
            Clear();
            this.bill_info.setVisible(false);
           
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        Clear();
        Close_Info();
        if(this.action == 2) 
        {
            ArrayList<DTO.bill_info> List_bill_info = bll_info.List_Bill_Info(this.id_bill);
            for (DTO.bill_info bill : List_bill_info)
            {
                bll_product.Update_Count_Product(bill.getId_product(), 1, bill.getCount());
            }
            bll_info.Del_All_Bill_Product(this.id_bill);
            bll.Del(bll.Info_Bill(this.id_bill));
        }
        this.id_bill = 0;
        this.action = 0;
        this.bill_info.setVisible(false);
        
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void bill_infoWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_bill_infoWindowClosing
        Clear();
        if(this.action == 2) 
        {
            ArrayList<DTO.bill_info> List_bill_info = bll_info.List_Bill_Info(this.id_bill);
            for (DTO.bill_info bill : List_bill_info)
            {
                bll_product.Update_Count_Product(bill.getId_product(), 1, bill.getCount());
            }
            bll_info.Del_All_Bill_Product(this.id_bill);
            bll.Del(bll.Info_Bill(this.id_bill));
        }
        this.id_bill = 0;
        this.action = 0;
        Close_Info();
        this.bill_info.setVisible(false);
    }//GEN-LAST:event_bill_infoWindowClosing

    private void bill_infoWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_bill_infoWindowActivated
        Load_Bill_Info();
    }//GEN-LAST:event_bill_infoWindowActivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Load();
    }//GEN-LAST:event_formWindowActivated

    private void jtb_bill_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_bill_infoMouseClicked
       On_Click_JTable_Bill_Info();
    }//GEN-LAST:event_jtb_bill_infoMouseClicked

    private void btn_del_bill_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del_bill_infoActionPerformed
        if(this.id_product == null)// Check exsit id Product before del bill info
        {
            JOptionPane.showMessageDialog(null, "You must select item bill info");
        }
        else
        {
            DTO.bill_info bill_info = bll_info.Info_Bill_Info(id_bill, id_product);
            int n = JOptionPane.showConfirmDialog(null,"You want *DELETE* this item ?","Question",JOptionPane.OK_CANCEL_OPTION);
            if(n == JOptionPane.YES_OPTION)
            {
                boolean x = bll_info.Del(bill_info, id_bill);
                bll_product.Update_Count_Product(bill_info.getId_product(), 1, bill_info.getCount());
            }
        }
    }//GEN-LAST:event_btn_del_bill_infoActionPerformed

    private void txt_id_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_customerActionPerformed
        if(bll_customer.Info_Customer(txt_id_customer.getText()) != null)
        {
            DTO.customer customer = bll_customer.Info_Customer(txt_id_customer.getText());
            txt_note.setText(customer.getFirst_name()+" " + customer.getLast_name()+ "\n" + customer.getPhone() + "\n" + customer.getAddress() + "\n" + bll_customer.Check_Name_Rank(customer.getId_rank()) );
            lb_sale.setText(String.valueOf(Sale(customer.getId_customer())));
            lb_shell_out.setText(String.valueOf(Long.parseLong(lb_sum_bill.getText()) * (100 - Sale(customer.getId_customer())) / 100));
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Id Customer don't esxits");
        }
    }//GEN-LAST:event_txt_id_customerActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        if(this.id_bill == 0)
        {
            JOptionPane.showMessageDialog(null, "You must select item bill");
        }
        else
        {
            int n = JOptionPane.showConfirmDialog(null,"You want *DELETE* this item ?","Question",JOptionPane.OK_CANCEL_OPTION);
            if(n == JOptionPane.YES_OPTION)
            {
                DTO.bill bill_info = bll.Info_Bill(this.id_bill);
                long sum = bill_info.getSum_bill();
                sum = -sum;
                bll_customer.Update_Accumulation(bill_info.getId_customer(), sum);
                bll_customer.Grownup_Rank(bill_info.getId_customer());
                ArrayList<DTO.bill_info> List_bill_info = bll_info.List_Bill_Info(this.id_bill);
                for (DTO.bill_info bill : List_bill_info)
                {
                    bll_product.Update_Count_Product(bill.getId_product(), 1, bill.getCount());
                }
                bll_info.Del_All_Bill_Product(this.id_bill);
                bll.Del(bll.Info_Bill(this.id_bill));
            }
            this.id_bill = 0;
            this.action = 0;
        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        Search();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.setVisible(false);
        DTO.Static_Object.list_bill_info = null;
    }//GEN-LAST:event_btn_backActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        DTO.Static_Object.list_bill_info = null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame bill_info;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_del_bill_info;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> jcb_payment;
    private javax.swing.JComboBox<String> jcb_search;
    private javax.swing.JSpinner js_count;
    private javax.swing.JTable jtb_bill;
    private javax.swing.JTable jtb_bill_info;
    private javax.swing.JLabel lb_sale;
    private javax.swing.JLabel lb_shell_out;
    private javax.swing.JLabel lb_sum_bill;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPanel pal_info;
    private javax.swing.JFormattedTextField txt_id_customer;
    private javax.swing.JFormattedTextField txt_id_product;
    private javax.swing.JTextArea txt_note;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
