/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinhtruong
 */
public class receive extends javax.swing.JFrame {

    /**
     * Creates new form receive
     */
    
    private int id_receive;
    // use to see info and edit data 
    private String id_product;
    
    private int action;
    
    /*
        action = 0 : see table
        action = 1 : see info
        action = 2 : add
    */
    public receive() {
        initComponents();
        this.id_receive = 0;
        this.action = 0;
        this.id_product = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receive_info = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jcb_product = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        js_count = new javax.swing.JSpinner();
        txt_cost = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_receive_info = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        btn_del_receive = new javax.swing.JButton();
        btn_add_receive = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn_ok = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcb_producer = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lb_sum_receive = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_receive = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_load = new javax.swing.JButton();
        btn_info = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        pal_search = new javax.swing.JPanel();
        jcb_search = new javax.swing.JComboBox<>();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();

        receive_info.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                receive_infoWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                receive_infoWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                receive_infoWindowActivated(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_title.setText("Title");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(522, 522, 522)
                .addComponent(lb_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_title)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("X");

        jLabel8.setText("Product");

        jLabel9.setText("Cost");

        jLabel10.setText("Count");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcb_product, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_count, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel8)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel9)
                        .addGap(124, 124, 124)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(js_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtb_receive_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Product", "Name Product", "Cost", "Count", "Sum"
            }
        ));
        jtb_receive_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_receive_infoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtb_receive_info);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_del_receive.setText("Del");
        btn_del_receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del_receiveActionPerformed(evt);
            }
        });

        btn_add_receive.setText("Add");
        btn_add_receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_receiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_add_receive, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_del_receive, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_del_receive)
                    .addComponent(btn_add_receive))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ok.setText("Ok");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok)
                    .addComponent(btn_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Infomation  Receive");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel3)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Producer:");

        jcb_producer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_producerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jcb_producer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_producer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Sum:");

        lb_sum_receive.setText("0");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_sum_receive, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lb_sum_receive))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout receive_infoLayout = new javax.swing.GroupLayout(receive_info.getContentPane());
        receive_info.getContentPane().setLayout(receive_infoLayout);
        receive_infoLayout.setHorizontalGroup(
            receive_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receive_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receive_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(receive_infoLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        receive_infoLayout.setVerticalGroup(
            receive_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receive_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receive_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Management Receive");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtb_receive.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Receive", "Name Producer", "Name Staff", "Date", "Total"
            }
        ));
        jtb_receive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_receiveMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_receive);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_load.setText("Load");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        btn_info.setText("Infomation");
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_del.setText("Del");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btn_load, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_info, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_load)
                    .addComponent(btn_info)
                    .addComponent(btn_add)
                    .addComponent(btn_del)
                    .addComponent(btn_back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcb_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search ID Receive", "Search Name Producer", "Search Name Staff", "Search Date" }));

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pal_searchLayout = new javax.swing.GroupLayout(pal_search);
        pal_search.setLayout(pal_searchLayout);
        pal_searchLayout.setHorizontalGroup(
            pal_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pal_searchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcb_search, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search)
                .addContainerGap())
        );
        pal_searchLayout.setVerticalGroup(
            pal_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pal_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pal_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pal_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pal_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //---------------------------------         Function use frame  ----------------------------------
    
    BLL.bll_receive bll = new BLL.bll_receive();
    
    BLL.bll_receive_info bll_info = new BLL.bll_receive_info();
    
    BLL.bll_staff bll_staff = new BLL.bll_staff();
    
    BLL.bll_producer bll_producer = new BLL.bll_producer();
    
    BLL.bll_product bll_product = new BLL.bll_product();
    
    private DefaultTableModel model = new DefaultTableModel();
    
    
    private String Date_Now()
    {
        LocalDateTime x = LocalDateTime.now();
        String date = x.format(DateTimeFormatter.ISO_LOCAL_DATE);
        return date;
    }
    
    private String Time_Now()
    {
        LocalDateTime x = LocalDateTime.now();
        String Time = x.format(DateTimeFormatter.ISO_LOCAL_TIME);
        String t = Time.substring(0,8);
        return t;
    }
    
    
    
    /*
        Hàm load các phieu nhap có trong DataBase
    */
    
    
    private void Load()
    {
        
        String header_vi[] = {""};
        String header_en[] = {};
        model = (DefaultTableModel) jtb_receive.getModel();
        if(model.getRowCount() > 0)
            model.setRowCount(0);//trả về table rỗng
        // Nhap lieu vao table
        ArrayList<DTO.receive> List_Receive = bll.List_Receive();
        for (DTO.receive receive : List_Receive)
            AddRow(receive);
    }
    
    
    
    /*
        Hàm đưa giá trị của phieu nhap vào Jtable
    */
    
    private String Name_Producer(int id)
    {
        if(id == 0) return null;
        else
        {
            DTO.producer producer = bll_producer.Info_Producer(id);
            return producer.getName_producer();
        }
    }
    
    private String Name_Staff(String id)
    {
        if(id == null || id.equals("") == true) return null;
        else
        {
            DTO.staff nv = bll_staff.Info_Staff(id);
            return nv.getFirst_name()+" "+ nv.getLast_name();
        }
    }
    
    private void AddRow(DTO.receive receive)
    {
        model = (DefaultTableModel) jtb_receive.getModel();
        model.addRow(new Object[] {receive.getId(), Name_Producer(receive.getId_producer()), Name_Staff(receive.getId_staff()),receive.getDate_time(), receive.getSum_receive()});
    }
    
    
    
    
    private void Load_Receive_Info()
    {
        model = (DefaultTableModel) jtb_receive_info.getModel();
        if(model.getRowCount() > 0)
            model.setRowCount(0);//trả về table rỗng
        // Nhap lieu vao table
        ArrayList<DTO.receive_info> List_receive_info = bll_info.List_Receive_Info(this.id_receive);
        for (DTO.receive_info receive_info : List_receive_info)
            AddRow_Producer_Info(receive_info);
        
        lb_sum_receive.setText(String.valueOf(bll_info.Sum_Receive(this.id_receive)));
        
        if(jcb_product.getItemCount() == 0)
        {
            ArrayList<String> List_Product = bll_product.List_Name_Product();
            for(String name : List_Product)
                jcb_product.addItem(name);
        }
        if(jcb_producer.getItemCount() == 0)
        {
            ArrayList<String> List_Producer = bll_producer.List_Name_Producer();
            for(String name : List_Producer)
                jcb_producer.addItem(name);
        }
    }
    
    private void AddRow_Producer_Info(DTO.receive_info receive_info)
    {
        model = (DefaultTableModel) jtb_receive_info.getModel();
        model.addRow(new Object[] {receive_info.getId_product(), bll_product.Get_Name_Product_By_ID(receive_info.getId_product()), receive_info.getCost(), receive_info.getCount(), receive_info.getSum()});
    }
    
    /*
        Hàm đưa dữ liệu từ Table ra co TextBox, Combobox
    */
    
    
    private void On_Click_JTable_Receive()
    {
        model = (DefaultTableModel) jtb_receive.getModel();
        this.id_receive = Integer.parseInt(model.getValueAt(jtb_receive.getSelectedRow(),0).toString());
        System.out.println(this.id_receive);
    }
    
    private void On_Click_JTable_Receive_Info()
    {
        model = (DefaultTableModel) jtb_receive_info.getModel();
        this.id_product = (model.getValueAt(jtb_receive_info.getSelectedRow(),0).toString()); 
        System.out.println(this.id_product);
    }
    
    
    private String ID_Staff(String UserName)
    {
        DTO.staff nv = bll_staff.Info_Staff_By_User_Name(UserName);
        return nv.getId();
    }
    
    
    /*
        Hàm sử dụng cho Add, Update, Del. Đưa thông tin từ TextBox, Combobox vào đối tượng phieu nhap
    */
     private DTO.receive Get_Form()
    {
        DTO.receive receive = new DTO.receive();
        String x = (String) jcb_producer.getSelectedItem();
        String id_producer = x.substring(0, 2);
        receive.setId_producer(Integer.parseInt(id_producer));
        receive.setId_staff(this.ID_Staff(DTO.Static_Object.username));
        receive.setDate_time(Date_Now()+" "+Time_Now());
        receive.setSum_receive(Long.parseLong(lb_sum_receive.getText()));
        receive.setId(this.id_receive);
        return receive;
    }
    
     /*
        Hàm sử dụng để tìm kiếm các sản phẩm thỏa mãn với từ nvóa
     */
     
     
    private void Search()
    {
        model = (DefaultTableModel) jtb_receive.getModel();
        if(model.getRowCount() > 0)
            model.setRowCount(0);//trả về table rỗng
        
        if(txt_search.getText().equals("") == true)
            JOptionPane.showMessageDialog(null, "You must write \"Key word\"");
        ArrayList <DTO.receive> List_Receive_Search = bll.List_Search((jcb_search.getSelectedIndex()+1),txt_search.getText());
        for( DTO.receive receive : List_Receive_Search)
            AddRow(receive);
    }
     
    
    /*
        Hàm xóa các giá trị có trong textbox, combox
    */
    
    
    private void Clear()
    {
            //this.jcb_producer.setSelectedIndex(0);
            this.lb_sum_receive.setText("0");
            //this.jcb_product.setSelectedIndex(0);
            this.txt_cost.setText("");
    }
    
    
    
    
    
    private void Info_Receive()
    {
        if(jcb_producer.getItemCount() == 0)
        {
            ArrayList<String> List_Producer = bll_producer.List_Name_Producer();
            for(String name : List_Producer)
                jcb_producer.addItem(name);
        }
        DTO.receive receive = bll.Info_Receive(this.id_receive);
        System.out.println(receive.getId_producer()-1);
        int index = receive.getId_producer()-1;
        this.jcb_producer.setSelectedIndex(index);
        this.lb_sum_receive.setText(String.valueOf(receive.getSum_receive()));
    }
    
    
    private void See_Info()
    {
            this.txt_cost.setEditable(false);
            this.btn_add_receive.setVisible(false);
            this.btn_del_receive.setVisible(false);
            this.btn_ok.setVisible(false);
    }
    
    //Reset frame
    private void Close_Info()
    {
            this.txt_cost.setEditable(true);
            this.btn_add_receive.setVisible(true);
            this.btn_del_receive.setVisible(true);
            this.btn_ok.setVisible(true);
    }
     
    
    
    // --------------------------------           End         ----------------------------------
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Load();
    }//GEN-LAST:event_formWindowActivated

    private void jtb_receiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_receiveMouseClicked
        On_Click_JTable_Receive();
    }//GEN-LAST:event_jtb_receiveMouseClicked

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        if(this.id_receive == 0)
        {
            JOptionPane.showMessageDialog(null, "You must select item bill");
        }
        else
        {
            this.action = 1;
            this.receive_info.setVisible(true);
            this.receive_info.setSize(1105, 570);
            this.lb_title.setText("Infomation");
            See_Info();
            Info_Receive();
        }
    }//GEN-LAST:event_btn_infoActionPerformed

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadActionPerformed
        Load();
    }//GEN-LAST:event_btn_loadActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        this.id_receive = bll.Get_Max_ID_Receive();
        DTO.receive receive = new DTO.receive();
        receive.setId_producer(1);
        receive.setId(this.id_receive);
        receive.setDate_time(Date_Now() + " " + Time_Now());
        receive.setId_staff(this.ID_Staff(DTO.Static_Object.username));
        receive.setSum_receive((long) 0);
        bll.Add(receive);
        this.action = 2;
        this.receive_info.setVisible(true);
        this.receive_info.setSize(1105, 570);
        lb_title.setText("Add");
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        if(this.id_receive == 0)
        {
            JOptionPane.showMessageDialog(null, "You must select item bill");
        }
        else
        {
            DTO.receive_info receive_info = bll_info.Info_Receive_Info(this.id_receive, id_product);
            int n = JOptionPane.showConfirmDialog(null,"You want *DELETE* this item ?","Question",JOptionPane.OK_CANCEL_OPTION);
            if(n == JOptionPane.YES_OPTION)
            {
                ArrayList<DTO.receive_info> List_receive_info = bll_info.List_Receive_Info(this.id_receive);
                for (DTO.receive_info receive : List_receive_info)
                {
                    bll_product.Update_Count_Product(receive.getId_product(), 0, receive.getCount());
                }
                bll_info.Del_All_Receive_Info(this.id_receive);
                bll.Del(bll.Info_Receive(this.id_receive));
            }
            this.id_receive = 0;
            this.action = 0;
        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        Clear();
        Close_Info();
        if(this.action == 2) 
        {
            ArrayList<DTO.receive_info> List_receive_info = bll_info.List_Receive_Info(this.id_receive);
            for (DTO.receive_info receive_info : List_receive_info)
            {
                bll_product.Update_Count_Product(receive_info.getId_product(), 0, receive_info.getCount());
            }
            bll_info.Del_All_Receive_Info(this.id_receive);
            bll.Del(bll.Info_Receive(this.id_receive));
        }
        this.id_receive = 0;
        this.action = 0;
        this.receive_info.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void receive_infoWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_receive_infoWindowClosed
        
    }//GEN-LAST:event_receive_infoWindowClosed

    private void receive_infoWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_receive_infoWindowClosing
        Clear();
        Close_Info();
        if(this.action == 2) 
        {
            ArrayList<DTO.receive_info> List_receive_info = bll_info.List_Receive_Info(this.id_receive);
            for (DTO.receive_info receive_info : List_receive_info)
            {
                bll_product.Update_Count_Product(receive_info.getId_product(), 0, receive_info.getCount());
            }
            bll_info.Del_All_Receive_Info(this.id_receive);
            bll.Del(bll.Info_Receive(this.id_receive));
        }
        this.id_receive = 0;
        this.action = 0;
        this.receive_info.setVisible(false);
    }//GEN-LAST:event_receive_infoWindowClosing

    private void btn_add_receiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_receiveActionPerformed
        String txt = (String) jcb_product.getSelectedItem();
        String id_product = txt.substring(0, 10);
        System.out.println(id_product);
        
        if(bll_product.Check_Product(id_product) != true)
        JOptionPane.showMessageDialog(null, "ID doesn't exist");
        else
        {
            if(bll_info.Check_Receive_Info(id_receive, id_product) == true)
            {
                System.out.println(id_receive);
                DTO.product  info_product = bll_product.Info_Product(id_product);
                DTO.receive_info receive_info = new DTO.receive_info();
                receive_info.setId_receive(this.id_receive);
                receive_info.setId_product(id_product);
                receive_info.setCount((int) js_count.getValue());
                receive_info.setCost(Long.parseLong(txt_cost.getText()));
                long count = (int) js_count.getValue();
                long cost = Long.parseLong(txt_cost.getText());
                receive_info.setSum(cost  * count);       
                bll_info.Add(receive_info);
                bll_product.Update_Count_Product(receive_info.getId_product(), 1, receive_info.getCount());
            }
        }
    }//GEN-LAST:event_btn_add_receiveActionPerformed

    private void btn_del_receiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del_receiveActionPerformed
        if(this.id_product == null)
        {
            JOptionPane.showMessageDialog(null, "You must select item receive info");
        }
        else
        {
            DTO.receive_info receive_info = bll_info.Info_Receive_Info(this.id_receive, id_product);
            int n = JOptionPane.showConfirmDialog(null,"You want *DELETE* this item ?","Question",JOptionPane.OK_CANCEL_OPTION);
            if(n == JOptionPane.YES_OPTION)
            {
                boolean x = bll_info.Del(receive_info);
                bll_product.Update_Count_Product(receive_info.getId_product(), 0, receive_info.getCount());
            }
        }
    }//GEN-LAST:event_btn_del_receiveActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        if(this.action == 2)
        {
           DTO.receive receive =  Get_Form();
           bll.Update(receive);
           this.receive_info.setVisible(false);
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void jtb_receive_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_receive_infoMouseClicked
        On_Click_JTable_Receive_Info();
    }//GEN-LAST:event_jtb_receive_infoMouseClicked

    private void receive_infoWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_receive_infoWindowActivated
        Load_Receive_Info();
    }//GEN-LAST:event_receive_infoWindowActivated

    private void jcb_producerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_producerActionPerformed
        if(this.action != 1)
        {
            String x = (String) jcb_producer.getSelectedItem();
            String id_producer = x.substring(0, 2);
            bll_info.Del_All_Receive_Info(this.id_receive);
            jcb_product.removeAllItems();
            if(jcb_product.getItemCount() == 0)
            {
                ArrayList<String> List_Product = bll_product.List_Name_Product_By_Producer(Integer.parseInt(id_producer));
                for(String name : List_Product)
                    jcb_product.addItem(name);
            }
        }
    }//GEN-LAST:event_jcb_producerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        JFrame fm = new main();
        fm.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        Search();
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add_receive;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_del_receive;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcb_producer;
    private javax.swing.JComboBox<String> jcb_product;
    private javax.swing.JComboBox<String> jcb_search;
    private javax.swing.JSpinner js_count;
    private javax.swing.JTable jtb_receive;
    private javax.swing.JTable jtb_receive_info;
    private javax.swing.JLabel lb_sum_receive;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPanel pal_search;
    private javax.swing.JFrame receive_info;
    private javax.swing.JFormattedTextField txt_cost;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
